"""Controlled entity registry with exact-ID resolution and layered resolver proposals."""

from .benchmark import load_blinded_benchmark_stub, load_public_annotated_subset, run_blinded_benchmark
from .corpus_scale import load_public_scale_corpus
from .errors import (
    AmbiguousResolutionError,
    EntityRegistryError,
    FuzzyMergeRefusedError,
    OverwriteRefusedError,
)
from .registry import (
    ENTITY_BOUNDARY,
    ENTITY_TYPES,
    EXACT_MATCH_MODES,
    IDENTIFIER_SCHEMES,
    RESOLUTION_STATES,
    assert_record_immutable,
    initialize_registry,
    load_entity,
    load_registry,
    refuse_fuzzy_merge,
    register_alias,
    register_entity,
    register_identifier,
    registry_status,
    resolve_exact,
    validate_registry,
)
from .resolver import (
    CONFIDENCE_LEVELS,
    DIRECTED_IDENTITY_RELATIONS,
    DISPOSITION_DECISIONS,
    IDENTITY_RELATION_DISPOSITIONS,
    LEGACY_DISPOSITION_DECISIONS,
    LEGACY_TO_IDENTITY_RELATION,
    MATCH_LAYERS,
    PROPOSAL_STATES,
    RESOLVER_BOUNDARY,
    identity_relation_for,
    load_resolution_proposal,
    normalize_mention,
    propose_resolution,
    record_resolution_disposition,
    report_batch_collisions,
    resolver_status,
)

__all__ = [
    "CONFIDENCE_LEVELS",
    "DIRECTED_IDENTITY_RELATIONS",
    "DISPOSITION_DECISIONS",
    "ENTITY_BOUNDARY",
    "ENTITY_TYPES",
    "EXACT_MATCH_MODES",
    "IDENTIFIER_SCHEMES",
    "IDENTITY_RELATION_DISPOSITIONS",
    "LEGACY_DISPOSITION_DECISIONS",
    "LEGACY_TO_IDENTITY_RELATION",
    "MATCH_LAYERS",
    "PROPOSAL_STATES",
    "RESOLUTION_STATES",
    "RESOLVER_BOUNDARY",
    "AmbiguousResolutionError",
    "EntityRegistryError",
    "FuzzyMergeRefusedError",
    "OverwriteRefusedError",
    "assert_record_immutable",
    "identity_relation_for",
    "initialize_registry",
    "load_blinded_benchmark_stub",
    "load_entity",
    "load_public_annotated_subset",
    "load_public_scale_corpus",
    "load_registry",
    "load_resolution_proposal",
    "normalize_mention",
    "propose_resolution",
    "record_resolution_disposition",
    "refuse_fuzzy_merge",
    "register_alias",
    "register_entity",
    "register_identifier",
    "registry_status",
    "report_batch_collisions",
    "resolve_exact",
    "resolver_status",
    "run_blinded_benchmark",
    "validate_registry",
]
